import { MongoClient, ObjectId } from 'mongodb';
import dotenv from 'dotenv';
import path from 'path';
import readline from 'readline';
import { getFirebaseAdmin } from '../config/firebase';

dotenv.config({ path: path.resolve(__dirname, '../../../../.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017';
const DB_NAME = process.env.MONGODB_DB_NAME || 'EasyFundDB';

const FORCE = process.argv.includes('--force');

const adminEmails = (process.env.ADMIN_EMAILS || 'admin@easyfund.com')
  .split(',')
  .map((e) => e.trim().toLowerCase())
  .filter(Boolean);

const adminEmail = adminEmails[0];

const DEMO_PASSWORD = 'password123';

function generateSlug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '');
}

async function confirm(message: string): Promise<boolean> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(`${message} (y/N): `, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === 'y');
    });
  });
}

// ─── SEED DATA ────────────────────────────────────────────

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();

const users = [
  {
    _id: new ObjectId(),
    firebaseUid: 'seed-admin-001',
    email: adminEmail,
    name: 'Admin User',
    image: '',
    role: 'admin' as const,
    phone: '+1 (555) 100-0001',
    bio: 'Platform administrator for EasyFund. Ensuring safe and transparent crowdfunding for everyone.',
    location: 'San Francisco, CA',
    website: 'https://easyfund.com',
    verified: true,
    verificationLevel: 'full' as const,
    emailVerified: true,
    notificationPreferences: { emailNotifications: true, donationAlerts: true, campaignUpdates: true, marketingEmails: false },
    campaignCount: 0,
    totalRaised: 0,
    totalDonated: 250,
    savedCampaigns: [],
    createdAt: daysAgo(90),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    firebaseUid: 'seed-fundraiser-001',
    email: 'sarah@example.com',
    name: 'Sarah Johnson',
    image: '',
    role: 'fundraiser' as const,
    phone: '+1 (555) 200-0001',
    bio: 'Passionate about education and healthcare. Running campaigns to make a difference in underserved communities.',
    location: 'New York, NY',
    website: '',
    verified: true,
    verificationLevel: 'identity' as const,
    emailVerified: true,
    notificationPreferences: { emailNotifications: true, donationAlerts: true, campaignUpdates: true, marketingEmails: false },
    campaignCount: 3,
    totalRaised: 125700,
    totalDonated: 500,
    savedCampaigns: [],
    createdAt: daysAgo(60),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    firebaseUid: 'seed-fundraiser-002',
    email: 'mike@example.com',
    name: 'Mike Chen',
    image: '',
    role: 'fundraiser' as const,
    phone: '+1 (555) 200-0002',
    bio: 'Environmental activist and fundraiser. Believer in clean water and sustainable futures for all.',
    location: 'Austin, TX',
    website: '',
    verified: true,
    verificationLevel: 'email' as const,
    emailVerified: true,
    notificationPreferences: { emailNotifications: true, donationAlerts: true, campaignUpdates: true, marketingEmails: true },
    campaignCount: 2,
    totalRaised: 33980,
    totalDonated: 150,
    savedCampaigns: [],
    createdAt: daysAgo(45),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    firebaseUid: 'seed-user-001',
    email: 'emily@example.com',
    name: 'Emily Davis',
    image: '',
    role: 'user' as const,
    phone: '',
    bio: 'Supporting causes I believe in. Every small donation counts!',
    location: 'Chicago, IL',
    website: '',
    verified: true,
    verificationLevel: 'email' as const,
    emailVerified: true,
    notificationPreferences: { emailNotifications: true, donationAlerts: true, campaignUpdates: true, marketingEmails: false },
    campaignCount: 0,
    totalRaised: 0,
    totalDonated: 1250,
    savedCampaigns: [],
    createdAt: daysAgo(30),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    firebaseUid: 'seed-user-002',
    email: 'james@example.com',
    name: 'James Wilson',
    image: '',
    role: 'user' as const,
    phone: '',
    bio: 'Tech professional who wants to give back. Supporting education and environment campaigns.',
    location: 'Seattle, WA',
    website: '',
    verified: false,
    verificationLevel: 'none' as const,
    emailVerified: false,
    notificationPreferences: { emailNotifications: true, donationAlerts: true, campaignUpdates: false, marketingEmails: false },
    campaignCount: 0,
    totalRaised: 0,
    totalDonated: 375,
    savedCampaigns: [],
    createdAt: daysAgo(15),
    updatedAt: now,
  },
];

const categories = [
  { name: 'Education', slug: 'education', icon: 'book-open', description: 'Support educational initiatives', campaignCount: 3, color: '#3B82F6' },
  { name: 'Health', slug: 'health', icon: 'heart-pulse', description: 'Healthcare and medical causes', campaignCount: 3, color: '#EF4444' },
  { name: 'Environment', slug: 'environment', icon: 'leaf', description: 'Environmental conservation', campaignCount: 3, color: '#22C55E' },
  { name: 'Community', slug: 'community', icon: 'users', description: 'Community development projects', campaignCount: 2, color: '#10B981' },
  { name: 'Emergency', slug: 'emergency', icon: 'siren', description: 'Disaster relief and emergency aid', campaignCount: 2, color: '#F59E0B' },
  { name: 'Technology', slug: 'technology', icon: 'cpu', description: 'Technology and innovation', campaignCount: 2, color: '#6366F1' },
  { name: 'Arts & Culture', slug: 'arts-culture', icon: 'palette', description: 'Arts, culture, and creative projects', campaignCount: 2, color: '#EC4899' },
  { name: 'Sports', slug: 'sports', icon: 'trophy', description: 'Sports and athletics programs', campaignCount: 1, color: '#F97316' },
  { name: 'Animals', slug: 'animals', icon: 'paw-print', description: 'Animal welfare and conservation', campaignCount: 2, color: '#8B5CF6' },
];

const campaigns = [
  {
    _id: new ObjectId(),
    slug: 'build-a-school-in-rural-india',
    title: 'Build a School in Rural India',
    description: 'Help us build a school for 500 children in rural India who currently walk 10km to attend classes.',
    story: 'In the remote villages of Rajasthan, India, children walk over 10 kilometers each way to attend the nearest school. Many drop out by age 12. We want to build a modern school with classrooms, a library, and a computer lab right in the village center. This will serve over 500 children and transform the entire community.',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'education',
    location: 'Rajasthan, India',
    status: 'active',
    goal: 50000,
    amountRaised: 32500,
    supportersCount: 148,
    deadline: daysAgo(-60),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 2,
    commentsCount: 5,
    riskScore: 0,
    reportCount: 0,
    featured: true,
    trending: true,
    createdAt: daysAgo(30),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'help-children-fight-cancer',
    title: 'Help Children Fight Cancer',
    description: 'Supporting children battling cancer with treatment, nutrition, and emotional support.',
    story: 'Every year, thousands of children are diagnosed with cancer. Families struggle to afford treatment. We partner with childrens hospitals to cover treatment costs, provide nutrition packs, and offer counseling services. Your donation directly saves lives.',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'health',
    location: 'Boston, MA',
    status: 'active',
    goal: 100000,
    amountRaised: 78200,
    supportersCount: 312,
    deadline: daysAgo(-45),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 3,
    commentsCount: 12,
    riskScore: 0,
    reportCount: 0,
    featured: true,
    trending: true,
    createdAt: daysAgo(25),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'clean-water-for-african-villages',
    title: 'Clean Water for African Villages',
    description: 'Providing clean drinking water to 10 villages in sub-Saharan Africa through well drilling.',
    story: 'Over 780 million people worldwide lack access to clean water. We are drilling wells in 10 villages across Kenya and Uganda. Each well provides water for up to 500 people and lasts for 20+ years. Clean water means healthier children, more time for education, and economic growth.',
    image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'community',
    location: 'Nairobi, Kenya',
    status: 'active',
    goal: 25000,
    amountRaised: 18750,
    supportersCount: 89,
    deadline: daysAgo(-30),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 1,
    commentsCount: 3,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: true,
    createdAt: daysAgo(20),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'save-our-rainforests',
    title: 'Save Our Rainforests',
    description: 'Protecting 1,000 acres of Amazon rainforest from deforestation through land purchase.',
    story: 'The Amazon rainforest is being destroyed at an alarming rate. We are purchasing 1,000 acres of critical rainforest habitat to permanently protect it. This land is home to over 200 species of birds, 50 species of mammals, and countless insects. Once purchased, the land will be managed as a nature reserve in perpetuity.',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'environment',
    location: 'Amazon Basin, Brazil',
    status: 'active',
    goal: 40000,
    amountRaised: 15230,
    supportersCount: 112,
    deadline: daysAgo(-40),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 0,
    commentsCount: 2,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(15),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'community-food-bank-expansion',
    title: 'Community Food Bank Expansion',
    description: 'Expanding our food bank to serve 2x more families in need across the tri-state area.',
    story: 'Our food bank has been serving the community for 5 years. We have outgrown our current space and need to expand to a larger facility. This will allow us to serve 2,000 families per month instead of 1,000. We will also add a commercial kitchen for hot meal preparation.',
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'community',
    location: 'Hartford, CT',
    status: 'completed',
    goal: 15000,
    amountRaised: 15000,
    supportersCount: 67,
    deadline: daysAgo(5),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'self',
    milestones: [],
    updatesCount: 4,
    commentsCount: 8,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(60),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'emergency-disaster-relief-fund',
    title: 'Emergency Disaster Relief Fund',
    description: 'Providing immediate relief to communities affected by natural disasters worldwide.',
    story: 'Natural disasters strike without warning. Our emergency relief fund provides immediate shelter, food, water, and medical supplies to affected communities. We work with local organizations on the ground to ensure aid reaches those who need it most. Every dollar goes directly to disaster survivors.',
    image: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'emergency',
    location: 'Global',
    status: 'submitted',
    goal: 75000,
    amountRaised: 0,
    supportersCount: 0,
    deadline: daysAgo(-90),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 0,
    commentsCount: 0,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(3),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'clean-coding-bootcamp-for-refugees',
    title: 'Clean Coding Bootcamp for Refugees',
    description: 'Teaching web development skills to refugees for sustainable employment.',
    story: 'Refugees often struggle to find employment in their new countries. Our 12-week coding bootcamp teaches HTML, CSS, JavaScript, and React — skills that open doors to remote and local tech jobs. Graduates receive mentorship and job placement support.',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'education',
    location: 'Berlin, Germany',
    status: 'active',
    goal: 30000,
    amountRaised: 12400,
    supportersCount: 87,
    deadline: daysAgo(-45),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 2,
    commentsCount: 6,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(22),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'mobile-health-clinic-rural-areas',
    title: 'Mobile Health Clinic for Rural Areas',
    description: 'Bringing essential healthcare services to remote villages via a fully-equipped mobile clinic.',
    story: 'Millions of people in rural areas live hours from the nearest hospital. Our mobile health clinic brings doctors, basic diagnostics, and essential medications directly to these communities. Each stop can serve 100+ patients in a single day.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'health',
    location: 'Lima, Peru',
    status: 'active',
    goal: 60000,
    amountRaised: 38200,
    supportersCount: 194,
    deadline: daysAgo(-35),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 3,
    commentsCount: 9,
    riskScore: 0,
    reportCount: 0,
    featured: true,
    trending: true,
    createdAt: daysAgo(18),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'youth-community-garden-project',
    title: 'Youth Community Garden Project',
    description: 'Building a community garden to teach urban youth about nutrition, sustainability, and teamwork.',
    story: 'Urban neighborhoods often lack green spaces and fresh produce. We are converting an abandoned lot into a thriving community garden run by local youth. Kids will learn to grow vegetables, understand nutrition, and build leadership skills.',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'community',
    location: 'Detroit, MI',
    status: 'active',
    goal: 12000,
    amountRaised: 7800,
    supportersCount: 54,
    deadline: daysAgo(-25),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 1,
    commentsCount: 4,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(12),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'wildfire-recovery-housing-fund',
    title: 'Wildfire Recovery Housing Fund',
    description: 'Providing temporary and permanent housing solutions for families displaced by wildfires.',
    story: 'When wildfires swept through our community, hundreds of families lost everything. This fund provides temporary shelter, helps with deposits on new rentals, and supports rebuilding efforts for the most vulnerable families.',
    image: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'emergency',
    location: 'Santa Rosa, CA',
    status: 'active',
    goal: 90000,
    amountRaised: 45600,
    supportersCount: 267,
    deadline: daysAgo(-50),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 5,
    commentsCount: 18,
    riskScore: 0,
    reportCount: 0,
    featured: true,
    trending: true,
    createdAt: daysAgo(28),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'solar-panels-for-public-schools',
    title: 'Solar Panels for Public Schools',
    description: 'Installing solar panel systems on 5 public schools to reduce energy costs and teach sustainability.',
    story: 'Public schools spend thousands on electricity each year. By installing solar panels, we can cut energy costs by 60% and redirect those savings to classrooms. Students will also learn about renewable energy through real-time monitoring dashboards.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'environment',
    location: 'Phoenix, AZ',
    status: 'active',
    goal: 80000,
    amountRaised: 52000,
    supportersCount: 213,
    deadline: daysAgo(-40),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 4,
    commentsCount: 11,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: true,
    createdAt: daysAgo(25),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'street-art-mural-project',
    title: 'Street Art Mural Project',
    description: 'Transforming neglected urban walls into vibrant murals celebrating local culture and history.',
    story: 'Blank, neglected walls can drag down an entire neighborhood. Our project commissions local artists to create large-scale murals that celebrate the history, culture, and diversity of the community. Art has the power to inspire and unite.',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'arts-culture',
    location: 'Miami, FL',
    status: 'active',
    goal: 18000,
    amountRaised: 9300,
    supportersCount: 72,
    deadline: daysAgo(-20),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 1,
    commentsCount: 5,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(10),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'adaptive-sports-equipment-drive',
    title: 'Adaptive Sports Equipment Drive',
    description: 'Providing specialized sports equipment for athletes with disabilities to compete and thrive.',
    story: 'Athletes with disabilities deserve the same opportunities to compete. Specialized wheelchairs, prosthetics, and adaptive gear are expensive and often not covered by insurance. This campaign will equip 50+ athletes with the gear they need.',
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'sports',
    location: 'Portland, OR',
    status: 'active',
    goal: 25000,
    amountRaised: 16800,
    supportersCount: 128,
    deadline: daysAgo(-30),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 2,
    commentsCount: 7,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(15),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'open-source-healthcare-app',
    title: 'Open Source Healthcare App',
    description: 'Building a free, open-source app connecting patients in underserved areas with volunteer doctors.',
    story: 'Many communities lack access to basic healthcare guidance. Our open-source app will connect patients with volunteer doctors for free telemedicine consultations, symptom checking, and medication reminders. The code will be freely available for any community to deploy.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'technology',
    location: 'Austin, TX',
    status: 'active',
    goal: 40000,
    amountRaised: 22500,
    supportersCount: 156,
    deadline: daysAgo(-38),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 3,
    commentsCount: 10,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(20),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'wildlife-rescue-rehabilitation-center',
    title: 'Wildlife Rescue & Rehabilitation Center',
    description: 'Building a state-of-the-art facility to rescue, rehabilitate, and release injured wildlife.',
    story: 'Every year, thousands of wild animals are injured, orphaned, or displaced by human activity. Our new rehabilitation center will provide veterinary care, safe housing, and a path back to the wild for bears, eagles, foxes, and other native species.',
    image: 'https://images.unsplash.com/photo-1474511320723-9a56873571b7?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'animals',
    location: 'Asheville, NC',
    status: 'active',
    goal: 35000,
    amountRaised: 19700,
    supportersCount: 143,
    deadline: daysAgo(-33),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 2,
    commentsCount: 8,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(17),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'stem-lab-underserved-schools',
    title: 'STEM Lab for Underserved Schools',
    description: 'Equipping 3 underfunded schools with computer labs, robotics kits, and science equipment.',
    story: 'Students in low-income neighborhoods rarely get hands-on STEM experience. We are building fully equipped computer labs with 30 workstations, robotics kits, 3D printers, and science lab equipment at 3 schools serving 1,200+ students.',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'education',
    location: 'Atlanta, GA',
    status: 'active',
    goal: 55000,
    amountRaised: 31000,
    supportersCount: 178,
    deadline: daysAgo(-42),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 3,
    commentsCount: 14,
    riskScore: 0,
    reportCount: 0,
    featured: true,
    trending: false,
    createdAt: daysAgo(24),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'mental-health-support-teens',
    title: 'Mental Health Support for Teens',
    description: 'Providing free counseling and mental health resources for at-risk teenagers.',
    story: 'Teen mental health is in crisis. Our program offers free one-on-one counseling, group therapy sessions, and 24/7 crisis support for teenagers dealing with anxiety, depression, and trauma. No teen should face mental health struggles alone.',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'health',
    location: 'Denver, CO',
    status: 'active',
    goal: 28000,
    amountRaised: 14200,
    supportersCount: 96,
    deadline: daysAgo(-28),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 1,
    commentsCount: 5,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(14),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'ai-powered-learning-platform',
    title: 'AI-Powered Learning Platform',
    description: 'Developing an adaptive learning platform that personalizes education for every student.',
    story: 'Every student learns differently. Our AI-powered platform adapts lesson difficulty, pacing, and content style in real-time based on each student\'s performance and engagement. Initial pilots show 40% improvement in test scores.',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'technology',
    location: 'San Francisco, CA',
    status: 'active',
    goal: 65000,
    amountRaised: 28900,
    supportersCount: 167,
    deadline: daysAgo(-48),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 4,
    commentsCount: 12,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: true,
    createdAt: daysAgo(26),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'ocean-cleanup-marine-life',
    title: 'Ocean Cleanup & Marine Life',
    description: 'Removing plastic waste from coastal waters and protecting endangered marine species.',
    story: 'Our oceans are choking on plastic. Our team deploys collection systems in coastal waters, removes debris from coral reefs, and rehabilitates injured sea turtles and marine mammals. Every ton of plastic removed protects countless species.',
    image: 'https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'animals',
    location: 'Honolulu, HI',
    status: 'active',
    goal: 45000,
    amountRaised: 33100,
    supportersCount: 201,
    deadline: daysAgo(-37),
    fundraiserId: users[1]._id.toString(),
    fundraiserName: 'Sarah Johnson',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 3,
    commentsCount: 9,
    riskScore: 0,
    reportCount: 0,
    featured: true,
    trending: true,
    createdAt: daysAgo(21),
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    slug: 'community-music-education-center',
    title: 'Community Music Education Center',
    description: 'Opening a free music school offering lessons, instruments, and studio time to underserved youth.',
    story: 'Music changes lives. Our community center will offer free lessons in guitar, piano, drums, and voice, plus recording studio access. Studies show music education improves academic performance, discipline, and self-esteem in young people.',
    image: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    category: 'arts-culture',
    location: 'Nashville, TN',
    status: 'active',
    goal: 20000,
    amountRaised: 8500,
    supportersCount: 63,
    deadline: daysAgo(-22),
    fundraiserId: users[2]._id.toString(),
    fundraiserName: 'Mike Chen',
    fundraiserImage: '',
    fundraiserVerified: true,
    beneficiaryType: 'others',
    milestones: [],
    updatesCount: 1,
    commentsCount: 3,
    riskScore: 0,
    reportCount: 0,
    featured: false,
    trending: false,
    createdAt: daysAgo(8),
    updatedAt: now,
  },
];

const donations = [
  {
    _id: new ObjectId(),
    campaignId: campaigns[0]._id.toString(),
    campaignTitle: campaigns[0].title,
    campaignImage: campaigns[0].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[3]._id.toString(),
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    amount: 100,
    currency: 'USD',
    anonymous: false,
    message: 'Great cause! Education changes lives.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(20),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[0]._id.toString(),
    campaignTitle: campaigns[0].title,
    campaignImage: campaigns[0].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[4]._id.toString(),
    userName: 'James Wilson',
    userEmail: 'james@example.com',
    amount: 250,
    currency: 'USD',
    anonymous: false,
    message: 'Happy to support this!',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(18),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[1]._id.toString(),
    campaignTitle: campaigns[1].title,
    campaignImage: campaigns[1].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[3]._id.toString(),
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    amount: 500,
    currency: 'USD',
    anonymous: false,
    message: 'For all the brave kids fighting cancer.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(15),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[1]._id.toString(),
    campaignTitle: campaigns[1].title,
    campaignImage: campaigns[1].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[4]._id.toString(),
    userName: 'James Wilson',
    userEmail: 'james@example.com',
    amount: 75,
    currency: 'USD',
    anonymous: true,
    message: '',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(12),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[2]._id.toString(),
    campaignTitle: campaigns[2].title,
    campaignImage: campaigns[2].image,
    fundraiserName: 'Mike Chen',
    userId: users[3]._id.toString(),
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    amount: 50,
    currency: 'USD',
    anonymous: false,
    message: 'Clean water is a human right.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(10),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[3]._id.toString(),
    campaignTitle: campaigns[3].title,
    campaignImage: campaigns[3].image,
    fundraiserName: 'Mike Chen',
    userId: users[0]._id.toString(),
    userName: 'Admin User',
    userEmail: adminEmail,
    amount: 250,
    currency: 'USD',
    anonymous: false,
    message: 'Protecting the Amazon is critical for our planet.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(8),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[4]._id.toString(),
    campaignTitle: campaigns[4].title,
    campaignImage: campaigns[4].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[4]._id.toString(),
    userName: 'James Wilson',
    userEmail: 'james@example.com',
    amount: 50,
    currency: 'USD',
    anonymous: false,
    message: 'Everyone deserves to eat.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(25),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[0]._id.toString(),
    campaignTitle: campaigns[0].title,
    campaignImage: campaigns[0].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[0]._id.toString(),
    userName: 'Admin User',
    userEmail: adminEmail,
    amount: 100,
    currency: 'USD',
    anonymous: false,
    message: 'Supporting education in rural areas.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(5),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[6]._id.toString(),
    campaignTitle: campaigns[6].title,
    campaignImage: campaigns[6].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[3]._id.toString(),
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    amount: 200,
    currency: 'USD',
    anonymous: false,
    message: 'Education opens doors for everyone.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(16),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[7]._id.toString(),
    campaignTitle: campaigns[7].title,
    campaignImage: campaigns[7].image,
    fundraiserName: 'Mike Chen',
    userId: users[3]._id.toString(),
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    amount: 150,
    currency: 'USD',
    anonymous: false,
    message: 'Healthcare is a right, not a privilege.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(14),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[9]._id.toString(),
    campaignTitle: campaigns[9].title,
    campaignImage: campaigns[9].image,
    fundraiserName: 'Mike Chen',
    userId: users[4]._id.toString(),
    userName: 'James Wilson',
    userEmail: 'james@example.com',
    amount: 300,
    currency: 'USD',
    anonymous: false,
    message: 'Hope the families find shelter soon.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(20),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[10]._id.toString(),
    campaignTitle: campaigns[10].title,
    campaignImage: campaigns[10].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[0]._id.toString(),
    userName: 'Admin User',
    userEmail: adminEmail,
    amount: 500,
    currency: 'USD',
    anonymous: false,
    message: 'Solar energy is the future.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(12),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[13]._id.toString(),
    campaignTitle: campaigns[13].title,
    campaignImage: campaigns[13].image,
    fundraiserName: 'Mike Chen',
    userId: users[3]._id.toString(),
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    amount: 75,
    currency: 'USD',
    anonymous: false,
    message: 'Tech for good!',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(10),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[14]._id.toString(),
    campaignTitle: campaigns[14].title,
    campaignImage: campaigns[14].image,
    fundraiserName: 'Sarah Johnson',
    userId: users[4]._id.toString(),
    userName: 'James Wilson',
    userEmail: 'james@example.com',
    amount: 100,
    currency: 'USD',
    anonymous: false,
    message: 'Every animal deserves a chance.',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(8),
  },
  {
    _id: new ObjectId(),
    campaignId: campaigns[16]._id.toString(),
    campaignTitle: campaigns[16].title,
    campaignImage: campaigns[16].image,
    fundraiserName: 'Mike Chen',
    userId: users[3]._id.toString(),
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    amount: 250,
    currency: 'USD',
    anonymous: false,
    message: 'Protect our oceans!',
    status: 'completed',
    transactionId: `txn_${new ObjectId().toString().slice(0, 12)}`,
    createdAt: daysAgo(6),
  },
];

const notifications = [
  {
    _id: new ObjectId(),
    userId: users[0]._id.toString(),
    type: 'welcome',
    title: 'Welcome to EasyFund!',
    message: 'Your account has been set up as an admin. You now have full access to the platform management tools.',
    read: false,
    createdAt: daysAgo(90),
  },
  {
    _id: new ObjectId(),
    userId: users[0]._id.toString(),
    type: 'donation',
    title: 'New Donation Received',
    message: 'Admin User donated $250 to Save Our Rainforests.',
    read: false,
    createdAt: daysAgo(8),
  },
  {
    _id: new ObjectId(),
    userId: users[1]._id.toString(),
    type: 'campaign_milestone',
    title: 'Campaign Milestone Reached!',
    message: 'Help Children Fight Cancer has reached 75% of its goal!',
    read: true,
    createdAt: daysAgo(10),
  },
  {
    _id: new ObjectId(),
    userId: users[1]._id.toString(),
    type: 'donation',
    title: 'New Donation',
    message: 'Emily Davis donated $500 to Help Children Fight Cancer.',
    read: false,
    createdAt: daysAgo(15),
  },
];

// ─── SEED FUNCTION ────────────────────────────────────────

async function seed() {
  const client = new MongoClient(MONGODB_URI);

  try {
    await client.connect();
    const db = client.db(DB_NAME);

    console.log(`\n  EasyFund Seed Script`);
    console.log(`  Database: ${DB_NAME}`);
    console.log(`  Admin emails: ${adminEmails.join(', ')}\n`);

    if (!FORCE) {
      const userCount = await db.collection('users').countDocuments();
      if (userCount > 0) {
        const proceed = await confirm(
          `⚠️  ${userCount} user(s) already exist. This will REPLACE all data. Continue?`
        );
        if (!proceed) {
          console.log('Seed cancelled.');
          return;
        }
      }
    }

    console.log('\n🗑️  Dropping existing collections...');
    const collections = [
      'users', 'campaigns', 'donations', 'categories', 'notifications',
      'comments', 'campaign_updates', 'withdrawals', 'verification_requests',
      'saved_campaigns', 'follows', 'audit_logs', 'reports', 'payment_webhooks',
    ];
    for (const name of collections) {
      await db.collection(name).drop().catch(() => {});
    }

    console.log('\n🔥 Creating Firebase Auth accounts...');
    const firebaseApp = getFirebaseAdmin();
    const uidMap = new Map<string, string>();

    for (const user of users) {
      try {
        const userRecord = await firebaseApp.auth().createUser({
          email: user.email,
          password: DEMO_PASSWORD,
          displayName: user.name,
          emailVerified: true,
        });
        uidMap.set(user.firebaseUid, userRecord.uid);
        console.log(`   ✓ Created Firebase account: ${user.email} (${userRecord.uid})`);
      } catch (error: any) {
        if (error.code === 'auth/email-already-exists') {
          const existing = await firebaseApp.auth().getUserByEmail(user.email);
          uidMap.set(user.firebaseUid, existing.uid);
          console.log(`   ℹ Firebase account already exists: ${user.email} (${existing.uid})`);
        } else {
          console.error(`   ✗ Failed to create Firebase account for ${user.email}:`, error.message);
        }
      }
    }

    for (const user of users) {
      const realUid = uidMap.get(user.firebaseUid);
      if (realUid) {
        user.firebaseUid = realUid;
      }
    }

    console.log('👤 Seeding users...');
    await db.collection('users').insertMany(users);
    console.log(`   ✓ ${users.length} users created`);

    console.log('📂 Seeding categories...');
    await db.collection('categories').insertMany(categories);
    console.log(`   ✓ ${categories.length} categories created`);

    console.log('📢 Seeding campaigns...');
    await db.collection('campaigns').insertMany(campaigns);
    console.log(`   ✓ ${campaigns.length} campaigns created`);

    console.log('💰 Seeding donations...');
    await db.collection('donations').insertMany(donations);
    console.log(`   ✓ ${donations.length} donations created`);

    console.log('🔔 Seeding notifications...');
    await db.collection('notifications').insertMany(notifications);
    console.log(`   ✓ ${notifications.length} notifications created`);

    console.log('📊 Creating indexes...');
    await db.collection('users').createIndex({ email: 1 }, { unique: true });
    await db.collection('users').createIndex({ firebaseUid: 1 });
    await db.collection('users').createIndex({ role: 1 });

    await db.collection('campaigns').createIndex({ slug: 1 }, { unique: true });
    await db.collection('campaigns').createIndex({ status: 1, createdAt: -1 });
    await db.collection('campaigns').createIndex({ fundraiserId: 1 });
    await db.collection('campaigns').createIndex({ category: 1 });
    await db.collection('campaigns').createIndex({ featured: 1 });
    await db.collection('campaigns').createIndex({ title: 'text', description: 'text', story: 'text' });

    await db.collection('donations').createIndex({ campaignId: 1, createdAt: -1 });
    await db.collection('donations').createIndex({ userId: 1 });
    await db.collection('donations').createIndex({ status: 1 });

    await db.collection('notifications').createIndex({ userId: 1, createdAt: -1 });
    await db.collection('comments').createIndex({ campaignId: 1 });
    await db.collection('campaign_updates').createIndex({ campaignId: 1 });
    await db.collection('withdrawals').createIndex({ fundraiserId: 1 });
    await db.collection('verification_requests').createIndex({ userId: 1 });
    await db.collection('reports').createIndex({ reporterId: 1 });
    await db.collection('audit_logs').createIndex({ action: 1 });
    await db.collection('saved_campaigns').createIndex({ userId: 1, campaignId: 1 }, { unique: true });
    await db.collection('follows').createIndex({ followerId: 1 });
    console.log('   ✓ Indexes created');

    console.log('\n✅ Seed completed successfully!\n');
    console.log('  Test accounts:');
    console.log('  ─────────────────────────────────────────');
    console.log(`  🔐 Admin:     ${adminEmail} (role: admin)`);
    console.log('  📢 Fundraiser: sarah@example.com (role: fundraiser)');
    console.log('  📢 Fundraiser: mike@example.com (role: fundraiser)');
    console.log('  ❤️  Donor:     emily@example.com (role: user)');
    console.log('  ❤️  Donor:     james@example.com (role: user)');
    console.log('  ─────────────────────────────────────────');
    console.log(`  🔑 Password for all accounts: ${DEMO_PASSWORD}\n`);
    console.log('  These accounts are ready to use — Firebase Auth + MongoDB are synced.\n');

  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  } finally {
    await client.close();
  }
}

seed();
